CREATE TRIGGER AES_CATEGORIES_SEQ_TRG 
BEFORE INSERT ON AES_CATEGORY
FOR EACH ROW
BEGIN
SELECT AES_CATEGORIES_SEQ.NEXTVAL INTO :NEW.CATEGORY_ID FROM DUAL;
END;
/

CREATE TRIGGER AES_USERS_SEQ_TRG
BEFORE INSERT ON AES_USERS
FOR EACH ROW
BEGIN
SELECT AES_USERS_SEQ.NEXTVAL INTO :NEW.USER_ID FROM DUAL;
END;
/

CREATE TRIGGER AES_ROLES_SEQ_TRG
BEFORE INSERT ON AES_ROLES
FOR EACH ROW
BEGIN
SELECT AES_ROLES_SEQ.NEXTVAL INTO :NEW.ROLE_ID FROM DUAL;
END;
/

CREATE TRIGGER AES_FORMAT_SEQ_TRG 
BEFORE INSERT ON AES_FORMATS
FOR EACH ROW
BEGIN
SELECT AES_FORMATS_SEQ.NEXTVAL INTO :NEW.FORMAT_ID FROM DUAL;
END;
/

CREATE TRIGGER AES_ASSESSMENT_SEQ_TRG
BEFORE INSERT ON AES_ASSESSMENT
FOR EACH ROW
BEGIN
SELECT AES_ASSESSMENT_SEQ.NEXTVAL INTO :NEW.ASSESSMENT_ID FROM DUAL;
END;
/

INSERT INTO AES_FORMATS VALUES(0, 'True/False');
INSERT INTO AES_FORMATS VALUES(0, 'Multiple Choice');
INSERT INTO AES_FORMATS VALUES(0, 'Multiple Select');
INSERT INTO AES_FORMATS VALUES(0, 'Drag and Drop');
INSERT INTO AES_FORMATS VALUES(0, 'Essay');
INSERT INTO AES_FORMATS VALUES(0, 'Short Answer');
INSERT INTO AES_FORMATS VALUES(0, 'Code Snippet');

INSERT INTO AES_ROLES VALUES(0, 'System');
INSERT INTO AES_ROLES VALUES(0, 'Recruiter');
INSERT INTO AES_ROLES VALUES(0, 'Candidate');
INSERT INTO AES_ROLES VALUES(0, 'Trainer');

INSERT INTO AES_USERS VALUES(0, 'system@revature.com', 'System', 'System', null, null, 1, TO_DATE('2003/07/09', 'yyyy/mm/dd'));

INSERT INTO AES_USERS (USER_ID, EMAIL, FIRSTNAME, LASTNAME, ROLE_ID, DATE_PASS_ISSUED) 
  VALUES (0, 'aes.recruiter@gmail.com', 'David', 'Recruiter-Man', 2, '12-DEC-12');
INSERT INTO AES_SECURITY (USER_ID, PASS_WORD, VALID) 
  VALUES (2, '$2a$12$TrSIwMnG9pvPydMiPMSnYeCLn3IPtpB54rbrqkDIZVZvS2Hw2OBnS', 1);


--INSERT CANDIDATES
INSERT INTO AES_USERS (USER_ID, EMAIL, FIRSTNAME, LASTNAME, ROLE_ID, RECRUITER_ID, DATE_PASS_ISSUED) 
  VALUES (0, 'willie.c.jensen@gmail.com', 'Willie', 'Jensen', 3, 2, '5-JAN-17');
INSERT INTO AES_SECURITY (USER_ID, PASS_WORD, VALID) 
  VALUES (3, '$2a$12$TrSIwMnG9pvPydMiPMSnYeCLn3IPtpB54rbrqkDIZVZvS2Hw2OBnS', 1);
  
  --INSERT CANDIDATES
INSERT INTO AES_USERS (USER_ID, EMAIL, FIRSTNAME, LASTNAME, ROLE_ID, RECRUITER_ID, DATE_PASS_ISSUED) 
  VALUES (0, 'MattP@gmail.com', 'Matt', 'Pski', 3, 2, '5-JAN-17');
INSERT INTO AES_SECURITY (USER_ID, PASS_WORD, VALID) 
  VALUES (4, '$2a$12$TrSIwMnG9pvPydMiPMSnYeCLn3IPtpB54rbrqkDIZVZvS2Hw2OBnS', 1);
  
  --INSERT CANDIDATES
INSERT INTO AES_USERS (USER_ID, EMAIL, FIRSTNAME, LASTNAME, ROLE_ID, RECRUITER_ID, DATE_PASS_ISSUED) 
  VALUES (0, 'ChelleS@gmail.com', 'Chelle', 'Slay', 3, 2, '5-JAN-17');
INSERT INTO AES_SECURITY (USER_ID, PASS_WORD, VALID) 
  VALUES (5, '$2a$12$TrSIwMnG9pvPydMiPMSnYeCLn3IPtpB54rbrqkDIZVZvS2Hw2OBnS', 1);
  
INSERT INTO "ADMIN"."AES_ASSESSMENT" (ASSESSMENT_ID, USER_ID, GRADE, TIME_LIMIT, CREATED_TIMESTAMP, FINISHED_TIMESTAMP) 
  VALUES (0, 5, 99, 45, TO_DATE('2012-12-12 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2012-12-12 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "ADMIN"."AES_ASSESSMENT" (ASSESSMENT_ID, USER_ID, GRADE, TIME_LIMIT, CREATED_TIMESTAMP, FINISHED_TIMESTAMP) 
  VALUES (0, 4, 86, 45, TO_DATE('2012-12-12 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2012-12-12 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "ADMIN"."AES_ASSESSMENT" (ASSESSMENT_ID, USER_ID, GRADE, TIME_LIMIT, CREATED_TIMESTAMP, FINISHED_TIMESTAMP) 
  VALUES (0, 3, 67, 45, TO_DATE('2012-12-12 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2012-12-12 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO AES_CATEGORY VALUES(0, 'Java');

DROP TRIGGER AES_CATEGORIES_SEQ_TRG;
DROP TRIGGER AES_USERS_SEQ_TRG;
DROP TRIGGER AES_ROLES_SEQ_TRG;
DROP TRIGGER AES_FORMAT_SEQ_TRG;
DROP TRIGGER AES_ASSESSMENT_SEQ_TRG;

commit; 